DELETE http://localhost:3001/api/blogs/65620036e05fbd6a52d7c8a2
Authorization: Bearer xxx

# Replace id above with an existing id from your database, and replace token with valid token
# Should get a 204 response