POST http://localhost:3001/api/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpbmdvIiwiaWQiOiI2NTYwZjMzOGRiNTI1YTI2NDQ4YWI1ZTAiLCJpYXQiOjE3MDA4NTcwOTF9.o7HLGrylyDHKlOJS9B6DlRyOa2g7XxgdFwQieLOD0KY

{
    "username": "paul",
    "password": "12",
    "name": "Paul McCartney"
}

#replace token with valid token