POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpbmdvIiwiaWQiOiI2NTYyMTNkYWJkNzIzNjgxZGU2MTk4OGMiLCJpYXQiOjE3MDA5NTUzNTcsImV4cCI6MTcwMDk1ODk1N30.b6KE7ZqVdDCWdZOVQuinvvJIL2pfxcTzQ8sabSaEyQo

{
  "title": "Test Blog Entry",
  "author": "Derek Williams",
  "url": "https://soto.podaac.earthdatacloud.nasa.gov/?v=-301.7396635888,-132.8645101122633,-49.96540178764417,128.74468379050018&t=2023-11-20-T22%3A00%3A00Z",
  "likes": 0
}

#replace token with valid token